### ISSUE TITLE
Does not prevent problems with certain keywords or weird names

### ISSUE THREAD

**Issue by calmh** [bjones/safe_attributes#1]
While a great idea, this does not help with for example database columns named 'changed' (because a changed? method will be generated, triggering a DangerousAttributeError) or 'reply-to' (because the dash will cause things to explode).

Possibly it needs to hook in deeper, to prevent the creation of any methods at all for these columns.

**Comment by bjones** [comment]
Thanks, as the documentation notes there are other generated methods I did not prevent the creation of that may cause issues.  I'll look into how to prevent the creation of things like changed? for a column named 'changed'.  Haven't ever had a column with dashes before, but I suspect this is where you need quoted column names.  Again I'll take a look, and thanks for trying out this gem!

**Comment by calmh** [comment]
Yeah, it's of course braindead to have a column named like that to start with, so I can't blame you for not running into it. If you ever do, I can guarantee it's a right pain to handle.

**Comment by lukassfranklin** [comment]
I have also experienced a failure with the database column 'errors' triggering a DangerousAttributeError despite being in the bad_attribute_names list.

**Comment by bjones** [comment]
I've resolved the issues with 'changed' and 'errors' and will be posting a new gem shortly.

**Comment by bjones** [comment]
Regarding hyphens, google says try ActiveRecord::Base.generate_read_methods = false to turn off autogeneration of reader methods.  My guess is that this by itself isn't enough.  Did you try adding the hyphen'd method name to bad attributes?

**Comment by bjones** [comment]
Also added a test for hyphenated column names and did not have any issue with it... so I presume ActiveRecord 3.0.9 no longer has issues with hyphens in column names as I've done nothing special for it either.
