### ISSUE TITLE
Interferes with Devise validations

### ISSUE THREAD

**Issue by bjones** [bjones/safe_attributes#2]
From google searching it appears someone ran into an issue using safe_attributes and devise together due to another validation somewhere expecting the generated attribute methods to exist.  Steps to reproduce were given as use both gems in a project.

**Comment by simonmorley** [comment]
Did you fix this?

**Comment by bjones** [comment]
Did you have more details?

On Nov 18, 2011, at 11:21 AM, simonmorley
reply@reply.github.com
wrote:

**Comment by simonmorley** [comment]
I have the same issue - you get one of two errors. One with login, the password is always incorrect. The second, when registering - it tells you password can't be blank and must match each other. 

In the development log, you see no particular error other than:

  Parameters: {"utf8"=>"✓", "authenticity_token"=>"K8NKYDTY9DCLFz9xEwrWQR5qkIIZ1DkaK4KZT34Etso=", "user"=>{"email"=>"test@polkaspots.com", "password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]"}, "commit"=>"Sign up"}

There's also a routing error when visiting /users/sign_out which I'm sure is related...

**Comment by bjones** [comment]
Okay, reproduced the issue, and will fix it.

**Comment by bjones** [comment]
Have a fix, difficult to create a standalone test.
