### ISSUE TITLE
Can't access 'attribute'

### ISSUE THREAD

**Issue by simonmorley** [bjones/safe_attributes#3]
Fantastic plugin - my legacy db has the column 'attribute'

Is it possible to do this - right now I'm getting an error:

NoMethodError: Attempt to call private method `attribute'

S

**Comment by bjones** [comment]
I just saw your message, I will check on this today or tonight when I
have the time.  If you fix before then just send a pull request.

Brian

On Nov 17, 2011, at 4:29 PM, simonmorley
reply@reply.github.com
wrote:

**Comment by simonmorley** [comment]
cool, thanks. I managed an interim fix by using select => attribute as attr but my devise is broken now.

**Comment by bjones** [comment]
I have seen someone mention a devise issue, can you update that issue
with details?

On Nov 18, 2011, at 7:47 AM, simonmorley
reply@reply.github.com
wrote:

**Comment by simonmorley** [comment]
have done... it's issue #2 s

**Comment by bjones** [comment]
Checked on this, there doesn't seem to be an issue with safe_attributes on this.  What the gem does is prevent clobbering the existing private method with a generated method for the attribute named 'attribute'.  You should be able to reference this attribute, and all others, using the other two methods described in the README of [:attribute] or read_attribute(:attribute).

**Comment by simonmorley** [comment]
Sorry, I'm a little confused about how to actually read this field. I've read the README but the methods don't work for me. I end up with an error:

undefined method `read_attribute' for...

**Comment by bjones** [comment]
I'd added some things to the test suite for this already, but here is one thing I find that doesn't work for your case.

ruby-1.9.3-p0 :078 > MyModel.new(:attribute => 'car')
ActiveRecord::UnknownAttributeError: unknown attribute: attribute

So you can't make a new object using :attribute as part of the hash.  This happens for the create/update Rails controller actions generally, so you'd have to work around it for now by deleting 'attribute' from the hash and setting it manually.

ruby-1.9.3-p0 :079 > m = MyModel.new
 => #<MyModel id: nil, class: nil, bad_attribute: nil, good_attribute: nil, changed: nil, errors: nil, comment-frequency: nil, attribute: nil> 
ruby-1.9.3-p0 :080 > m[:attribute] = 'foo'
 => "foo" 
ruby-1.9.3-p0 :081 > m.read_attribute(:attribute)
 => "foo" 
ruby-1.9.3-p0 :082 > m[:attribute]
 => "foo" 

All of these things seem to work fine for me.

**Comment by bjones** [comment]
Did some digging into rails and in this case I can't really do anything to resolve setting :attribute in either the new() or attributes=() because one is allowed to make a my_attribute= method that does something special, or to make my_attribute= private to prevent mass assignment.  Use of write_attribute() in these cases breaks that functionality.  The only recourse for something called 'attribute' is to not set it via mass assignment.

**Comment by simonmorley** [comment]
Thanks for the answer and email. A single column has never caused so much fuss. 

I found datamapper to cope better but it seems to be missing full support for a few things and it seems a bit too new to rely on.

Am still using your excellent plugin but in the end decided to try and rebuild the entire database / application to bring it up to date

S

On 27 Nov 2011, at 16:16, Brian Jones wrote:

> Did some digging into rails and in this case I can't really do anything to resolve setting :attribute in either the new() or attributes=() because one is allowed to make a my_attribute= method that does something special, or to make my_attribute= private to prevent mass assignment.  Use of write_attribute() in these cases breaks that functionality.  The only recourse for something called 'attribute' is to not set it via mass assignment.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/bjones/safe_attributes/issues/3#issuecomment-2888367

---

The information contained in this email and its attachments is confidential and may be the subject of legal, professional or other privilege. It is intended only for the named addressees and may not be disclosed to anyone else without consent from PolkaSpots Limited. If you are not the named addressee you must not use, disclose, distribute, copy, print or rely on the contents of this email and should destroy it immediately. Whilst PolkaSpots Limited takes care to protect its systems from electronic virus attack or other harmful event, the firm gives no warranty that this email message (including any attachments to it) is free of any virus or other harmful matter and accepts no responsibility for any loss or damage resulting from the recipient receiving, opening or using it. If you need any further information, please contact the originator of this message on +44 (0) 20 7183 1471.

PolkaSpots Limited is registered in the UK, number 05508105. Registered Office: 204 Buspace Studios, Conlan Street, London W10 5AP

## Website: www.polkaspots.com

**Comment by bjones** [comment]
Still checking on this but a default scope select as might be enough
to work around this and not need my gem at all.

On Nov 27, 2011, at 2:31 PM, simonmorley
reply@reply.github.com
wrote:

**Comment by bjones** [comment]
Using a scope with :select unfortunately marks the retrieved records as readonly.  Datamapper has been around quite a while and yes should handle this a bit better in that I believe it lets you map an attribute name to a column name quite easily.  I think it was the default ORM for Merb, but I have not heavily used it in quite some time so I'm unaware of the current state of Datamapper.
