### ISSUE TITLE
Error saving new model with "attribute" attribute

### ISSUE THREAD

**Issue by kmatthews812** [bjones/safe_attributes#4]
I think I found 1 case where your gem fails.  I can read and update models with an attribute column named "attribute", but I cannot save a new one when the attribute name is "attribute".  Other attribute names work fine for all methods.  

Try this with Ruby 1.9.2 and Rails 3.1.3

> rails g model TestModel

CreateTestModels.rb

``` ruby
class CreateTestModels < ActiveRecord::Migration
  def change
    create_table :test_models do |t|
      t.string :attribute
      t.timestamps
    end
  end
end
```

TestModel.rb

``` ruby
class TestModel < ActiveRecord::Base
  bad_attribute_names :attribute

  def blah= value
    self[:attribute] = value
  end

  def blah
    self[:attribute]
  end

end
```

> rails console
> Loading development environment (Rails 3.1.3)
> ruby-1.9.2-p290 :001 > t = TestModel.new
>  => #<TestModel id: nil, attribute: nil, created_at: nil, updated_at: nil> 
> ruby-1.9.2-p290 :002 > t.blah = 'blah'
>  => "blah" 
> ruby-1.9.2-p290 :003 > t.save
>    (512.0ms)  BEGIN
>   SQL (295.2ms)  INSERT INTO `test_models` (`attribute`, `created_at`, `updated_at`) VALUES ('blah', '2011-12-09 06:00:21', '2011-12-09 06:00:21')
>    (305.7ms)  ROLLBACK
> ArgumentError: wrong number of arguments (0 for 1)
>     from /Users/kmatthews812/.rvm/gems/ruby-1.9.2-p290/gems/activerecord-3.1.3/lib/active_record/attribute_methods/read.rb:141:in `attribute'
>     from /Users/kmatthews812/.rvm/gems/ruby-1.9.2-p290/gems/activemodel-3.1.3/lib/active_model/dirty.rb:143:in`attribute_change'
>     from /Users/kmatthews812/.rvm/gems/ruby-1.9.2-p290/gems/activemodel-3.1.3/lib/active_model/dirty.rb:117:in `block in changes'

The strange part is that the data is actually saved to the database.  The error is thrown after the data is saved and the rollback never occurs.  Any ideas on how to fix this?  I have no ability to change the database column name, as this is a legacy database.  

Thanks!

**Comment by bjones** [comment]
I'll look at it this weekend.  For now override save & ignore error.

On Dec 9, 2011, at 12:04 AM, Kevin Matthews
reply@reply.github.com
wrote:

**Comment by bjones** [comment]
I've looked this over a bit.  ActiveModel essentially requires this method be implemented, def attribute(attr).  I've tried changing some code in ActiveModel and ActiveRecord to use a different method name but I think this would potentially break too much stuff.  I'm pondering another alternative fix.  I don't think I'll have a working solution for a while though.

**Comment by kmatthews812** [comment]
OK, thanks for looking into it.  I will probably end up changing the column
name.

Kev

On Sun, Dec 11, 2011 at 2:37 PM, Brian Jones <
reply@reply.github.com

**Comment by bjones** [comment]
I'm going to close this and just document that a column named 'attribute' won't work.

**Comment by kmatthews812** [comment]
Cool.
On Jan 3, 2012 3:00 PM, "Brian Jones" <
reply@reply.github.com>
wrote:
