### ISSUE TITLE
safe_attributes breaks password and password_confirmation fields for Devise objects 

### ISSUE THREAD

**Issue by WattsInABox** [bjones/safe_attributes#5]
We have a User class in our Rails project that uses Devise for authentication. The `password` and `password_confirmation` fields in devise, by default, work a little differently.

In short, those fields conflict with the override of #read_attribute_for_validation. 

Rather than focusing on fixing this directly, my vote is that we get rid of requiring the safe attributes railtie by default. 

I can work on this if you approve of this solution. Thanks!

**Comment by bjones** [comment]
Ok, send pull request.  Devise was working at one point...

On Aug 21, 2012, at 11:34 AM, Billy Watson notifications@github.com wrote:

We have a User class in our Rails project that uses Devise for
authentication. The password and password_confirmation fields in devise, by
default, work a little differently.

In short, those fields conflict with the override of
#read_attribute_for_validation.

Rather than focusing on fixing this directly, my vote is that we get rid of
requiring the safe attributes railtie by default.

I can work on this if you approve of this solution. Thanks!

—
Reply to this email directly or view it on
GitHubhttps://github.com/bjones/safe_attributes/issues/5.

**Comment by WattsInABox** [comment]
Just now getting started on the pull request and trying to sneak this in while at work. Getting an error when it's trying to create the SQLite database. Any ideas?

```
/Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in `initialize': unable to open database file (SQLite3::CantOpenException)
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in `new'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in `sqlite3_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:309:in `new_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:319:in `checkout_new_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:241:in `block (2 levels) in checkout'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in `loop'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in `block in checkout'
    from /Users/williamrwatson/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:233:in `checkout'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:96:in `block in connection'
    from /Users/williamrwatson/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in `mon_synchronize'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:95:in `connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:404:in `retrieve_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_specification.rb:170:in `retrieve_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_specification.rb:144:in `connection'
    from /Users/williamrwatson/development/safe_attributes/spec/safe_attributes/safe_attributes_spec.rb:4:in `<top (required)>'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `block in load_spec_files'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `map'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in `load_spec_files'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:22:in `run'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in `run'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in `block in autorun'
```

**Comment by bjones** [comment]
It doesn't make the db dir, sorry.

On Aug 29, 2012, at 1:48 PM, Billy Watson notifications@github.com wrote:

Just now getting started on the pull request and trying to sneak this in
while at work. Getting an error when it's trying to create the SQLite
database. Any ideas?

/Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in
`initialize': unable to open database file
(SQLite3::CantOpenException)
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in
`new'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/sqlite3_adapter.rb:26:in
`sqlite3_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:309:in
`new_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:319:in
`checkout_new_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:241:in
`block (2 levels) in checkout'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in
`loop'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:236:in
`block in checkout'
    from /Users/williamrwatson/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in
`mon_synchronize'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:233:in
`checkout'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:96:in
`block in connection'
    from /Users/williamrwatson/.rvm/rubies/ruby-1.9.2-p320/lib/ruby/1.9.1/monitor.rb:201:in
`mon_synchronize'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:95:in
`connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:404:in
`retrieve_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_specification.rb:170:in
`retrieve_connection'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/activerecord-3.2.8/lib/active_record/connection_adapters/abstract/connection_specification.rb:144:in
`connection'
    from /Users/williamrwatson/development/safe_attributes/spec/safe_attributes/safe_attributes_spec.rb:4:in
`<top (required)>'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in
`load'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in
`block in load_spec_files'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in
`map'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/configuration.rb:780:in
`load_spec_files'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/command_line.rb:22:in
`run'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:69:in
`run'
    from /Users/williamrwatson/.rvm/gems/ruby-1.9.2-p320@safe_attributes/gems/rspec-core-2.11.1/lib/rspec/core/runner.rb:8:in
`block in autorun'

 —
Reply to this email directly or view it on
GitHubhttps://github.com/bjones/safe_attributes/issues/5#issuecomment-8134489.

**Comment by bjones** [comment]
I fixed the missing db/ dir issue.

**Comment by WattsInABox** [comment]
Okay thanks. Sorry, works has been crazy. Want to get that pull request back to you this week.

**Comment by bjones** [comment]
See also the solution to Issue #2 from a year ago.

**Comment by WattsInABox** [comment]
I already issued the pull request removing the automatic inclusion of safe_attributes into all ActiveRecord objects. Will this solution work? I've updated the documentation, as well. 

https://github.com/bjones/safe_attributes/pull/7

**Comment by bjones** [comment]
Closing this, I wrote a slightly different patch that does not alter the default use of the railtie, but does give you the option of changing the require in your Gemfile so the railtie is not used.
